[package]
name = "URL_parser"
version = "0.1.0"
authors = ["Matthew Villegas <matthew.villegas@knights.ucf.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
url = "2.1.1"