[package]
name = "sha-1"
version = "0.1.0"
authors = ["mattvillegas <matthew.villegas@knights.ucf.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha1 = "0.6.0"