[package]
name = "jewels_and_stones"
version = "0.1.0"
authors = ["mattvillegas <matthew.villegas@knights.ucf.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
